spring:
  application:
    name: Wincert-webfaramework

  profiles:
    active:
      - local

---
spring:
  profiles: local

logging:
  level:
    org:
      springframework: info
    tomcat: trace
    com.wincert.framework: debug
  file.max-size: 50MB
  file.max-history: 15
  pattern:
    console: "%d{yyyyMMdd HH:mm:ss.SSS} [%thread] %-3level %logger{5} - %msg %n"
    file: "%d{yyyyMMdd HH:mm:ss.SSS} [%thread] %-3level %logger{5} - %msg %n"
  file:
    path: c:\temp\
    name: wincert.log




---
spring:
  profiles: develop

logging:
  level:
    org:
      springframework: info
    tomcat: trace
    com.wincert.framework: DEBUG
  file.max-size: 50MB
  file.max-history: 15
  pattern:
    console: "%d{yyyyMMdd HH:mm:ss.SSS} [%thread] %-3level %logger{5} - %msg %n"
    file: "%d{yyyyMMdd HH:mm:ss.SSS} [%thread] %-3level %logger{5} - %msg %n"
  file:
    path:
    name: